# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "image" {
  type    = string
  default = "UbuntuServer"
}

variable "location" {
  type    = string
  default = "eastus2"
}

variable "rg" {
  type    = string
  default = "Compute-RG"
}

variable "size" {
  type    = string
  default = "Standard_E2bds_v5"
}

variable "version" {
  type    = string
  default = "01"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "azure-arm" "autogenerated_1" {
  client_id                         = "f0c456e1-0e0d-4521-a59e-c28227a29548"
  client_secret                     = "qbz8Q~ERUmVQPYSd.lywFuaMvuuT2iZg.DfMobTg"
  image_offer                       = "${var.image}"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  location                          = "${var.location}"
  managed_image_name                = "app${var.version}"
  managed_image_resource_group_name = "${var.rg}"
  os_type                           = "Linux"
  subscription_id                   = "9cbf6dff-2f97-4886-830d-bf3620a92698"
  tenant_id                         = "c9f06d72-d0c9-4779-9036-b8ef09f162e3"
  vm_size                           = "${var.size}"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    inline         = ["sudo apt-get update", "sudo apt-get upgrade -y", "sudo apt-get -y install nginx", "mkdir Hello-Packer"]
    inline_shebang = "/bin/sh -x"
  }

}
